# Permalinks
permalink:        pretty

# Setup
title:            Awesome Programmer
tagline:          Code, cookies, universe
paginate:         5
baseurl:          /
author:
  name:           Rostyslav Kurylo
  url:            https://twitter.com/RostakaGmfun
  email:          rostawesomegd@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/RostakaGmfun/rostakagmfun.github.io
description:      The diary of awesome programmer and cool guy. Programming, 3d graphics, c++, gamedev, opengl, linux, coding, rostakagmfun
desc:             The diary of awesome programmer and cool guy.
keywords:         programming, 3d graphics, c++, gamedev, OpenGL, linux, coding, rostakagmfun
motto:            CEO of the universe. Pissing on your heads.

exclude: [update.sh]
